# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/groom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/groom.proto\x12\x05groom\",\n\x17RoomRegistrationRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"+\n\x18RoomRegistrationResponse\x12\x0f\n\x07room_id\x18\x01 \x01(\x05\x32Z\n\x05Groom\x12Q\n\x0eRegisterToRoom\x12\x1e.groom.RoomRegistrationRequest\x1a\x1f.groom.RoomRegistrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.groom_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_start=29
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_end=73
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_start=75
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_end=118
  _globals['_GROOM']._serialized_start=120
  _globals['_GROOM']._serialized_end=210
# @@protoc_insertion_point(module_scope)
